### ISSUE TITLE
Expected Performance

### ISSUE THREAD

**Issue by karandwivedi42** [bkj/basenet#1]
Hi!

I was curious as to what final performance did you get with this model? Were you able to reproduce the results from official code?

I am asking because I tried a lot of variations (before the official code was released) but never got close to their accuracy, so I was curious about others' experience with the same.

**Comment by bkj** [comment]
Reproduce results from what official code?  Which code/paper are you talking about?

~ Ben

**Comment by karandwivedi42** [comment]
Oh I am sorry! I meant to ask this comment in ripenet repo (which is based on ENAS). Sorry, I will close this issue.

I meant to ask if the pytorch ripenet code gives as good performance as the official enas code.

**Comment by bkj** [comment]
Ah got it -- no worries.  Open an issue over there and I can discuss further.
